spring:
  application:
      name: data-intake-rest-service
  jpa:
   hibernate:
    ddl-auto: none
  datasource:
   url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
   driver-class-name: org.h2.Driver
  flyway:
   driver-class-name: org.h2.Driver
   locations: classpath:db/migration,classpath:db/vendor/{vendor}
#  profiles:
#   active: json-logs
  security:
   oauth2:
     resourceserver:
       jwt:
         issuer-uri:  ${AUTH_SERVER_URI:'http://localhost:9000'}
         jwk-set-uri: http://${AUTH_SERVER:localhost}:${AUTH_SERVER_PORT:9000}/oauth2/jwks
  #Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
  ai:
   openai:
     api-key: ${OPENAI_API_KEY}
  # Enable Virtual Threads - faster, reduces memory footprint
  threads:
    virtual:
      enabled: true
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  tracing:
    sampling:
      probability: 0.5
logging:
  pattern:
    level: |
      [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
  level:
    org.jemberai.dataintake: trace
    org.zalando.logbook: trace
    # org.springframework.orm: trace
    root: ${LOG_LEVEL:info}
  include-application-name: true
server:
  port: 8082
org:
  jemberai:
    milvusDatabaseName: "data_intake_local"
    cryptography:
      jemberKeyId: "9a7630cd-8083-429c-82c0-a76d12d69f13"
      jemberAesKey: "NW67Ztk36sn8gzo8atUYspcrdSuv1Tn94gZhEQbb094="
      jemberHmacKey: "bP8hfE2sl7kJwHbi3mnmXUeLP6AGnDErQv3+mcADtU0="
    datasource:
      primary:
        url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
        driver-class-name: org.h2.Driver
        username: sa
        password: admin
        name: primary
      keystore:
        url: jdbc:h2:mem:keystore;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
        driver-class-name: org.h2.Driver
        username: sa
        password: admin
        name: keystore
      keystore-flyway:
        url: jdbc:h2:mem:keystore;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
        driver-class-name: org.h2.Driver
        username: sa
        password: admin
    jpa:
      primary:
          hibernate:
            ddl-auto: none
      keystore:
        hibernate:
          ddl-auto: none
logbook:
  predicate:
    exclude:
        - path: /actuator/**