name: jember-ai-local
services:
  auth-server:
    container_name: auth-server
    image: quay.io/jember.ai/spring-auth-server:${AUTH_IMAGE_TAG:-latest}
    restart: always
    ports:
      - 8888:8888
    environment:
      - JEMBER_SECRET=jember-client
      - SERVER_PORT=8888
      - LOG_LEVEL=warn
  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_IMAGE_TAG:-14-alpine}
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./cfg/postgres/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
    labels:
      org.springframework.boot.ignore: true
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.14
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2024-09-13T20-26-02Z-cpuv1
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio_data:/data
    command: minio server /minio_data --console-address ":9001"
    # Spring Boot was failing on health check, but it was working fine from the CL. Commenting out for now.
#    healthcheck:
#      test: ["CMD", "curl", "--fail", "http://localhost:9000/minio/health/live || exit 1"]
#      interval: 30s
#      start_period: 15s
#      timeout: 20s
#      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.10
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
   default:
    name: milvus

volumes:
  minio_data:
  etcd_data:
  milvus_data: