name: Publish Data Intake RAG Service Image (amd64 / arm64)

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: ['main'] # main branch only.
    paths-ignore:
      - '**.md'
      - '.idea/**/*'
      - '.mvn/**/*'
      - 'mvnw'
      - 'mvnw.cmd'
      - '.vscode/**/*'
      - '**/.env.example'
      - '.github/ISSUE_TEMPLATE/**/*'

env:
  REGISTRY_LOGIN_SERVER: quay.io
  IMAGE: jember.ai/data-intake-rag-service

jobs:
  push_multi_platform_to_registries:
    name: Push image to quay
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@main

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set projects Maven version to GitHub Action GUI set version
        run: ./mvnw versions:set "-DnewVersion=${{ steps.bump.outputs.new_tag }}" --no-transfer-progress

      - name: Build with Maven
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -B clean verify --no-transfer-progress -P coverage org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=jemberai_data-intake-rag-service

      - name: 'Login to Quay'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ vars.QUAY_USER }}
          password: ${{ secrets.QUAY_KEY }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type,raw,value=${{github.event.inputs.releaseversion}}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Grab the new version from [Quay.io](https://quay.io/repository/jember.ai/data-intake-rag-service/tag/${{ github.event.inputs.releaseversion }})
            
            ```
              docker pull quay.io/jember.ai/data-intake-rag-service:${{ github.event.inputs.releaseversion }} 
            ``` 
            ### Things that changed in this release
            ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.bump.outputs.new_tag }}