name: Qodana
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_verify:
    name: Run Merge Checks
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      checks: write
      pull-requests: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@main

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          architecture: x64
          cache: 'maven'

      - name: Build with Maven
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: mvn -B clean verify

#      - name: Archive coverage data
#        uses: actions/upload-artifact@v4
#        with:
#          name: maven-coverage-data-jacoco
#          path: .qodana/code-coverage
#
#      - name: 'Qodana Scan'
#        uses: JetBrains/qodana-action@v2024.1
#        env:
#          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
#        with:
#          pr-mode: false